### ISSUE TITLE
Getting a fatal error when upgrading to the latest version

### ISSUE THREAD

**Issue by jtsimoes** [am1cable/nodebb-plugin-simple-spoiler#3]
I'm getting this error when upgrading to v0.2.3 and when having a topic with code (```) inside a spoiler ([s]):

```
2019-02-11T15:11:59.286Z [4567/1109] - error: uncaughtException: text is not defined
ReferenceError: text is not defined
    at replaceSpoilerContent (/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js:18:33)
    at Object.parsePost [as method] (/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js:33:19)
    at /home/ectua/NodeBB/src/plugins/hooks.js:133:12
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:2516:9
    at replenish (/home/ectua/NodeBB/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/home/ectua/NodeBB/node_modules/async/dist/async.js:995:17)
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:969:16
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:2518:13
    at /home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js:59:9
    at /home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js:117:21 {"error":{},"stack":"ReferenceError: text is not defined\n    at replaceSpoilerContent (/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js:18:33)\n    at Object.parsePost [as method] (/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js:33:19)\n    at /home/ectua/NodeBB/src/plugins/hooks.js:133:12\n    at /home/ectua/NodeBB/node_modules/async/dist/async.js:2516:9\n    at replenish (/home/ectua/NodeBB/node_modules/async/dist/async.js:1011:17)\n    at iterateeCallback (/home/ectua/NodeBB/node_modules/async/dist/async.js:995:17)\n    at /home/ectua/NodeBB/node_modules/async/dist/async.js:969:16\n    at /home/ectua/NodeBB/node_modules/async/dist/async.js:2518:13\n    at /home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js:59:9\n    at /home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js:117:21","exception":true,"date":"Mon Feb 11 2019 16:11:59 GMT+0100 (CET)","process":{"pid":1109,"uid":1001,"gid":1001,"cwd":"/home/ectua/NodeBB","execPath":"/usr/bin/node","version":"v8.15.0","argv":["/usr/bin/node","/home/ectua/NodeBB/app.js"],"memoryUsage":{"rss":169320448,"heapTotal":132460544,"heapUsed":104268816,"external":1199100}},"os":{"loadavg":[0.4658203125,0.36376953125,0.2431640625],"uptime":1443872},"trace":[{"column":33,"file":"/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js","function":"replaceSpoilerContent","line":18,"method":null,"native":false},{"column":19,"file":"/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js","function":"Object.parsePost [as method]","line":33,"method":"parsePost [as method]","native":false},{"column":12,"file":"/home/ectua/NodeBB/src/plugins/hooks.js","function":null,"line":133,"method":null,"native":false},{"column":9,"file":"/home/ectua/NodeBB/node_modules/async/dist/async.js","function":null,"line":2516,"method":null,"native":false},{"column":17,"file":"/home/ectua/NodeBB/node_modules/async/dist/async.js","function":"replenish","line":1011,"method":null,"native":false},{"column":17,"file":"/home/ectua/NodeBB/node_modules/async/dist/async.js","function":"iterateeCallback","line":995,"method":null,"native":false},{"column":16,"file":"/home/ectua/NodeBB/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":13,"file":"/home/ectua/NodeBB/node_modules/async/dist/async.js","function":null,"line":2518,"method":null,"native":false},{"column":9,"file":"/home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js","function":null,"line":59,"method":null,"native":false},{"column":21,"file":"/home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js","function":null,"line":117,"method":null,"native":false}]}
2019-02-11T15:11:59.289Z [4567/1109] - error: text is not defined
ReferenceError: text is not defined
    at replaceSpoilerContent (/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js:18:33)
    at Object.parsePost [as method] (/home/ectua/NodeBB/node_modules/nodebb-plugin-simple-spoiler/library.js:33:19)
    at /home/ectua/NodeBB/src/plugins/hooks.js:133:12
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:2516:9
    at replenish (/home/ectua/NodeBB/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/home/ectua/NodeBB/node_modules/async/dist/async.js:995:17)
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:969:16
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:2518:13
    at /home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js:59:9
    at /home/ectua/NodeBB/node_modules/nodebb-plugin-xkcd-embed/index.js:117:21
2019-02-11T15:11:59.292Z [4567/1109] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-02-11T15:11:59.294Z [4567/1109] - info: [app] Web server closed to connections.
[cluster] Child Process (1109) has exited (code: 1, signal: null)

```

Before upgrading to this new plugin version, code and spoilers were working perfectly.

And besides that, my NodeBB shows me that the lastest version of this plugin is v0.2.3 and npm package shows me that is actually v0.3.0 and here in your Github repo the latest version is v0.3.1...
Maybe you forgot to do `npm publish` (?)

**Comment by jtsimoes** [comment]
The topic had the following text:

[s=]
```
var text = '{"name":"John", "birth":"1986-12-14", "city":"New York"}';
var obj = JSON.parse(text, function (key, value) {
  if (key == "birth") {
    return new Date(value);
  } else {
    return value;
  }
});
document.getElementById("demo").innerHTML = obj.name + ", " + obj.birth; 
```
[/s]

**Comment by 4m2c4bl3** [comment]
hey! the correct version needs to be 3.0.1 - i don't know why nodebb is being so slow to get that version. I'll try making a version upgrade when I get home today and see if that fixes it. 

You can solve this for now by manually changing the version number in package.json to 3.0.1

**Comment by jtsimoes** [comment]
Fixed on npm and on NodeBB. Lastest version is now 3.0.1 on both.

All fine now, the error is gone. Thanks!
